# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		account_fr_chorus

TRYTON_DEPENDS +=	account
TRYTON_DEPENDS +=	account_invoice
TRYTON_DEPENDS +=	company
TRYTON_DEPENDS +=	party
TRYTON_DEPENDS += 	party_siret

RUN_DEPENDS +=		www/py-requests${MODPY_FLAVOR}

.include <bsd.port.mk>
