# $OpenBSD: Makefile,v 1.3 2019/04/28 20:51:48 sthen Exp $

MODPY_EGG_VERSION =	5.0.2
TRYTON_MODULE =		commission_waiting

TRYTON_DEPENDS +=	account \
			account_invoice \
			commission

.include <bsd.port.mk>
