# $OpenBSD$

MODPY_EGG_VERSION =	5.0.1
TRYTON_MODULE =		stock

TRYTON_DEPENDS +=	company
TRYTON_DEPENDS += 	currency
TRYTON_DEPENDS +=	party
TRYTON_DEPENDS +=	product

RUN_DEPENDS +=		databases/py-sql${MODPY_FLAVOR}

.include <bsd.port.mk>
