# $OpenBSD: Makefile,v 1.3 2019/04/28 20:51:47 sthen Exp $

MODPY_EGG_VERSION =	5.0.2
TRYTON_MODULE =		account_dunning_fee

TRYTON_DEPENDS +=	account_dunning \
			account_product

.include <bsd.port.mk>
