# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		account_eu

TRYTON_DEPENDS +=	account
TRYTON_DEPENDS += 	account_invoice
TRYTON_DEPENDS +=	company
TRYTON_DEPENDS +=	currency

.include <bsd.port.mk>
