# $OpenBSD: Makefile,v 1.3 2019/04/28 20:51:47 sthen Exp $

MODPY_EGG_VERSION =	5.0.2
TRYTON_MODULE =		account_eu

TRYTON_DEPENDS +=	account \
			account_invoice \
			company \
			currency

.include <bsd.port.mk>
