# $OpenBSD: Makefile,v 1.5 2020/03/02 07:23:33 semarie Exp $

MODPY_EGG_VERSION =	5.0.5
TRYTON_MODULE =		sale_supply_drop_shipment

TRYTON_DEPENDS +=	company \
			purchase \
			purchase_request \
			sale \
			sale_supply \
			stock

.include <bsd.port.mk>
