# $OpenBSD: Makefile,v 1.7 2020/07/03 21:12:28 sthen Exp $

MODPY_EGG_VERSION =	5.0.6
TRYTON_MODULE =		sale_supply_drop_shipment

TRYTON_DEPENDS +=	company \
			purchase \
			purchase_request \
			sale \
			sale_supply \
			stock

.include <bsd.port.mk>
