# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		stock_shipment_measurements

TRYTON_DEPENDS +=	product \
			product_measurements \
			stock

TEST_TRYTON_DEPENDS +=	stock_package

.include <bsd.port.mk>
