# $OpenBSD: Makefile,v 1.2 2019/02/22 07:24:35 semarie Exp $

MODPY_EGG_VERSION =	5.2.0
TRYTON_MODULE =		account_statement_rule

TRYTON_DEPENDS +=	account \
			account_invoice \
			account_statement \
			bank \
			company \
			party

.include <bsd.port.mk>
