# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		account_payment_stripe

TRYTON_DEPENDS +=	account
TRYTON_DEPENDS +=	account_payment
TRYTON_DEPENDS +=	party

#RUN_DEPENDS +=		devel/py-stripe{MODPY_FLAVOR}	# TODO: not ported

.include <bsd.port.mk>
