# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		account_payment_stripe

TRYTON_DEPENDS +=	account \
			account_payment \
			party

#RUN_DEPENDS +=		devel/py-stripe{MODPY_FLAVOR}	# TODO: not ported

.include <bsd.port.mk>
