# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		account_dunning_email

TRYTON_DEPENDS +=	account_dunning
TRYTON_DEPENDS +=	account_dunning_letter
TRYTON_DEPENDS +=	party

.include <bsd.port.mk>
