# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		party

TRYTON_DEPENDS +=	country

RUN_DEPENDS +=		databases/py-sql${MODPY_FLAVOR}
RUN_DEPENDS +=		devel/py-stdnum${MODPY_FLAVOR}
#RUN_DEPENDS +=		phonenumbers # optional, not ported, XXX installed by test

.include <bsd.port.mk>
