# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		analytic_invoice

TRYTON_DEPENDS +=	account_invoice
TRYTON_DEPENDS += 	analytic_account

TRYTON_TEST_DEPENDS +=	account_asset

.include <bsd.port.mk>
