# $OpenBSD: Makefile,v 1.4 2019/04/28 20:51:47 sthen Exp $

MODPY_EGG_VERSION =	5.0.3
TRYTON_MODULE =		account_dunning_letter

TRYTON_DEPENDS += 	account \
			account_dunning \
			company \
			party

.include <bsd.port.mk>
