# $OpenBSD: Makefile,v 1.4 2019/04/28 20:51:49 sthen Exp $

MODPY_EGG_VERSION =	5.0.3
TRYTON_MODULE =		product_classification_taxonomic

TRYTON_DEPENDS +=	product_classification

.include <bsd.port.mk>
