# $OpenBSD: Makefile,v 1.3 2019/04/28 20:51:48 sthen Exp $

MODPY_EGG_VERSION =	5.0.2
TRYTON_MODULE =		analytic_purchase

TRYTON_DEPENDS +=	analytic_account \
			analytic_invoice \
			purchase

.include <bsd.port.mk>
