# $OpenBSD$

SUBDIR =

SUBDIR +=	account
SUBDIR +=	account_fr
SUBDIR +=	account_invoice
SUBDIR +=	account_invoice_stock
SUBDIR +=	account_product
SUBDIR +=	company
SUBDIR +=	country
SUBDIR +=	currency
SUBDIR +=	party
SUBDIR +=	party_siret
SUBDIR +=	product
SUBDIR +=	purchase
SUBDIR +=	stock

SUBDIR +=	proteus
SUBDIR +=	sao
SUBDIR +=	tryton
SUBDIR +=	trytond

.include <bsd.port.subdir.mk>
