# $OpenBSD$

SUBDIR =

SUBDIR +=	account
SUBDIR +=	account_asset
SUBDIR +=	account_be
SUBDIR +=	account_credit_limit
SUBDIR +=	account_de_skr03
SUBDIR +=	account_deposit
SUBDIR +=	account_dunning
SUBDIR +=	account_dunning_email
SUBDIR +=	account_dunning_fee
SUBDIR +=	account_dunning_letter
SUBDIR +=	account_es
SUBDIR +=	account_eu
SUBDIR +=	account_fr
SUBDIR +=	account_fr_chorus
SUBDIR +=	account_invoice
SUBDIR +=	account_invoice_correction
SUBDIR +=	account_invoice_history
SUBDIR +=	account_invoice_line_standalone
SUBDIR +=	account_invoice_stock
SUBDIR +=	account_payment
SUBDIR +=	account_payment_clearing
SUBDIR +=	account_payment_sepa
SUBDIR +=	account_payment_sepa_cfonb
#SUBDIR +=	account_payment_stripe
SUBDIR +=	account_product
SUBDIR +=	account_statement
SUBDIR +=	account_statement_ofx
SUBDIR +=	analytic_account
SUBDIR +=	analytic_invoice
SUBDIR +=	bank
SUBDIR +=	company
SUBDIR +=	country
SUBDIR +=	currency
SUBDIR +=	party
SUBDIR +=	party_siret
SUBDIR +=	product
SUBDIR +=	purchase
SUBDIR +=	stock

SUBDIR +=	proteus
SUBDIR +=	sao
SUBDIR +=	tryton
SUBDIR +=	trytond

.include <bsd.port.subdir.mk>
