# $OpenBSD$

MODPY_EGG_VERSION =	5.0.0
TRYTON_MODULE =		analytic_account

TRYTON_DEPENDS +=	account
TRYTON_DEPENDS +=	company
TRYTON_DEPENDS += 	currency
TRYTON_DEPENDS +=	party

RUN_DEPENDS +=		databases/py-sql${MODPY_FLAVOR}

.include <bsd.port.mk>
