# $OpenBSD: Makefile,v 1.3 2019/04/28 20:51:50 sthen Exp $

MODPY_EGG_VERSION =	5.0.3
TRYTON_MODULE =		sale_supply

TRYTON_DEPENDS +=	purchase \
			purchase_request \
			sale \
			stock

.include <bsd.port.mk>
